### ISSUE TITLE
Investigate making results from Nightly AR runs to be publicly available

### ISSUE THREAD

**Issue by AMZN-Dk** [o3de/sig-testing#10]
In order to hand off the ownership of RCA and reporting of Nightly AR failures to the SIGs we need to make the reporting of the nightly results available publicly.

This issue is to look into the requirements and dependencies to make this possibly. A couple of options we are considering:

1. Use tooling to auto-cut issues for failed tests into GHI under needs-sig and needs-triage label, then reporting the list of issues daily
2. Make the overall results of nightly runs publicly available, then hand ownership and responsibility of reporting issues from failures to the SIGs

There may be other options to enable this process, this issue is to perform the investigation into these options.

**Comment by Kadino** [comment]
This is partially being driven by SIG-Build, however SIG-Testing should keep pressure on this.

**Comment by Kadino** [comment]
Need to define next steps, or an RFC on (for example) the cost. This will also require improving the experience of looking at nightly runs.

**Comment by Kadino** [comment]
SIG-Build has delivered this as https://jenkins.build.o3de.org/job/O3DE_periodic-incremental-daily/job/development/
