### ISSUE TITLE
SIG-Testing 11/30 release notes

### ISSUE THREAD

**Issue by Ulrick28** [o3de/sig-testing#13]
Please fill any info related to the below for the 11/30 release notes: Note this has a due date of Friday Nov 12th, 2021

 * Features
 * Bug fixes (GHI list if possible)
 * Deprecations
 * Known issues

**Comment by dialweb6** [comment]
Features

- ** Parallel Python Test Execution and Standardization **
     - Test Automation Framework that allows for parallel execution of python tests using multiple editor instances
- ** LyTestTools support for Linux **
     - LyTestTools automation framework now supports executing test cases on Linux

**Comment by Kadino** [comment]
Known Issues:

- Certain 3rdParty python modules cannot load in the Editor runtime on Linux, which blocks multiple tests using EditorPythonBindings.

**Comment by dialweb6** [comment]
We don't have any GHI issues as all the work was tracked internally

**Comment by tonybalandiuk** [comment]
Closing. Release has shipped.
