### ISSUE TITLE
SIG Reviewer Nomination

### ISSUE THREAD

**Issue by SWMasterson** [o3de/sig-testing#15]
### Nomination Guidelines
**Reviewer Nomination Requirements**
* 6+ contributions successfully submitted to O3DE
* 100+ lines of code changed across all contributions submitted to O3DE
* 2+ O3DE Reviewers or Maintainers that support promotion from Contributor to Reviewer
* Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month
-------
### ReviewerNomination
-------------------

I would like to nominate: SWMasterson, to become a Reviewer on behalf of sig-testing. I verify that they have fulfilled the prerequisites for this role.

* Nominee's GitHub Profile https://github.com/swmasterson

*Reviewers & Maintainers that support this nomination should comment in this issue.*

**Comment by Kadino** [comment]
@SWMasterson do you now have the proper permissions?
