### ISSUE TITLE
Proposed SIG-Testing meeting agenda for July-01-21

### ISSUE THREAD

**Issue by Kadino** [o3de/sig-testing#2]
## Meeting Details

- **Date/Time:** July 1, 2021 @ 18:00 UTC / 2:00pm EDT / 11:00am PDT
- **Location:** [Discord SIG-Testing Voice Room](https://discord.gg/6cbrfZgyfg)
- **Moderator:** Sean Sweeney (Kadino)
- **Note Taker** Sean Sweeney (Kadino)

The [SIG-Testing Meetings](https://github.com/o3de/sig-testing/tree/main/meetings) repo contains the history past calls, including a link to the agenda, recording, notes, and resources.

## SIG Updates

* There are no updates since the previous meeting, as this is the first meeting! We are currently trying to bootstrap this SIG, to prepare it for success when it is handed off to the Linux Foundation. The current meeting participants are expected to be the majority of the members of this public SIG through launch.

## Meeting Agenda

* Attendee introductions
* Review and ratify SIG Charter at https://github.com/o3de/sig-testing/pull/1

## Outcomes from Discussion topics

* Charter review had significant discussion, pointed to additional changes

## Action Items

* Update charter based on feedback (Kadino)
* Upload meeting minutes to repo (Kadino)
* Re-review and ratify charter at next SIG-Testing meeting (sig-testing)

## Open Discussion Items

List any additional items below!

**Comment by AMZN-Dk** [comment]
This meeting was held. Will create a new issue for the next meeting on 8/27.
