### ISSUE TITLE
SIG Maintainer Nomination for smurly

### ISSUE THREAD

**Issue by smurly** [o3de/sig-testing#45]
### Nomination Guidelines

**Maintainer Nomination Requirements**
* Has been a Reviewer for 2+ months
* 8+ reviewed Pull Requests in the previous 2 months
* 200+ lines of code changed across all reviewed Pull Request
* 2+ O3DE Maintainers that support the promotion from Reviewer to Maintainer
* Requirements to retain the Reviewer role: 4+ Pull Requests reviewed per month

-------
##### Fill out the template below including nominee GitHub user name, desired role and personal GitHub profile
-------------------

I would like to nominate: ***smurly***, to become a ***Maintainer*** on behalf of ***sig-testing***. I verify that they have fulfilled the prerequisites for this role.

* Nominee's GitHub Profile ***[https://github.com/smurly](https://github.com/smurly)***

*Reviewers & Maintainers that support this nomination should comment in this issue.*

**Comment by AMZN-Dk** [comment]
I support Smurly in the nomination for testing SIG maintainer.

**Comment by Kadino** [comment]
I also support this, and will resolve the issue after the GH team membership status is modified.

**Comment by jromnoa** [comment]
I support @smurly for sig-testing maintainer
