### ISSUE TITLE
Determine if additional Ubuntu tests are required and potentially put them in place. 

### ISSUE THREAD

**Issue by tonybalandiuk** [o3de/sig-testing#46]
During the 22.05.0 release we discovered this issue: https://github.com/o3de/o3de/issues/9502

This issue was randomly discovered by someone testing the night before the release.
I am raising this here so that SIG-Platform can consider when/where this sort of testing (opening files from the file explorer) should be tested and potentially put the necessary processes in place. 

Since it's platform-related testing it seems like it should fall under the responsibility of this sig to decide what should happen with this.

**Comment by Kadino** [comment]
Also unsure what the thrust of this request is. As mentioned by @spham-amzn in the linked ticket, the original issue is with OS-level functionality: https://www.omgubuntu.co.uk/2018/05/nautilus-remove-ability-launch-binaries-apps

The application binaries themselves function properly on Ubuntu, which is already assured by existing tests in the Linux build pipeline. As far as SIG-Testing ownership, no additional systemic testing appears necessary and the test-tools appear sufficiently tested. Additional individual tests of product functionality are always nice to add, but that functionality its tests should be maintained by other SIGs.
