### ISSUE TITLE
Define proactive outreach to other SIGs

### ISSUE THREAD

**Issue by Kadino** [o3de/sig-testing#48]
While SIG-Testing is a group organized to simplify test-writing for other SIGs, our charter and RFCs are fairly passive. SIG-Testing should proactively reach out to other SIGs to help clarify how we can assist and/or collaborate with them.

Recommend the ways we can reach out, critical talking points, and a cadence for regularly performing outreach. This should result in creating new tasks to define the outreach content, and to perform the initial outreach.

Initially suggested points:
* SIG-Testing can assist other SIGs by:
  * Help provide, improve, or take ownership of shared test tools
  * Consulting to help determine their level of risk / risk-acceptance
  * Reviewing any new test automation in pull requests
* Outreach approach could include:
  * Attend meetings of other SIGs, to help clarify - meetings are listed in O3DE calendar
  * Could clarify what we do in Discord text channel
  * Designate ambassador to other SIGs (may personalize which is good, may pigeonhole which is less good)

**Comment by AMZN-Dk** [comment]
Working with Release SIG on this messaging, plan is is to go out on 8/22

**Comment by AMZN-Dk** [comment]
Closing this out. Release SIG has handled this messaging in previous SIG meetings.
