### ISSUE TITLE
2023 SIG-Testing Chair/Co-Chair Elections

### ISSUE THREAD

**Issue by Kadino** [o3de/sig-testing#74]
## SIG chair / co-chair elections for 2023

SIG-Testing should organize an election for the new year. Per the [Elections Guide](https://github.com/o3de/community/blob/main/O3DE%20Elections/O3DE%20Elections%20Guide.md), at least one Election Official should be identified before proceeding. This official should be assigned this issue, and drive the process forward.

## The chair / co-chair roles

The chair and co-chair serve equivalent roles in the governance of the SIG and are only differentiated by title in that the highest vote-getter is the chair and the second-highest is the co-chair. The chair and co-chair are expected to govern together in an effective way and split their responsibilities to make sure that the SIG operates smoothly and has the availability of a chairperson at any time.

Unless distinctly required, the term "chairperson" refers to either/both of the chair and co-chair. If a chair or co-chair is required to perform a specific responsibility for the SIG they will always be addressed by their official role title.

Chairs are not required to provide "on-call" support of any kind as part of their chairship. The O3D Foundation is responsible for addressing any high-severity issues related to documentation or community which would impact the immediate operation of the O3DE project or may result in legal liability of the O3D Foundation.

### Responsibilities

- Schedule and proctor regular SIG meetings on a monthly cadence, or as determined by the SIG.
- Planning and strategy for test automation for O3DE.
- Serve as a source of authority (and ideally wisdom) with regards to testing O3DE. Chairpersons are the ultimate arbiters of many documentation standards, processes, and practices.
- Act as representatives of the community, and provide advice to other SIGs, the Technical Steering Committee (TSC), and the Foundation on community building and management.
- Coordinate with partners and the Linux Foundation and Marketing Committee regarding official community events.
- Regularly participate in O3DE discussion channels such as our mailing lists, GitHub discussions, and Discord.
- Maintain a release roadmap for the O3DE SIG area of discipline.

### Nomination requirements

- Nominees must be an active contributor to Open 3D Engine in some fashion.
- Nominees are not required to be reviewers or maintainers, but reviewer/maintainer status is something nominees should highlight.
- Nominees should have at least some familiarity with open source, and one of either technical writing or community management / building.

If you are nominated by somebody other than yourself, you're encouraged to provide your own statement (however brief). If you would like to decline a nomination, please do so on this issue before the nomination deadline.

### How to nominate

Nominations will be accepted beginning with the date of posting of this issue, and will be open until 2023-03-31 12:00 PM Pacific Time.

Nominate somebody (including yourself) by responding to this issue with:

1. A statement that the nominee should be nominated for a chair position in the Testing SIG.
2. Include any information on their work in O3DE (whether that is actively participating in Discord/forums/email, producing code submissions, producing docs submissions, or providing external tutorials or resources). If you are nominating yourself, provide a brief statement on your reasons for running for chairperson..
3. If you are nominating somebody else, make sure that they are @-ed by their GitHub alias so they receive a notification and can respond.
4. The name under which the nominee should be addressed. Nominees are allowed to contact the election proctor to have this name changed.
5. The GitHub username of the nominee. (Self-nominations need not include this; it's on your post.)
6. Nominee's Discord username. Chairpersons must be active in the O3DE Discord if elected.

By accepting a nomination you acknowledge that you believe you can faithfully execute the role required of a chairperson for sig-testing for the next 6-12 months. Chairpersons may relinquish their chairship at any time and for any reason.

If only one nomination is received, nominations will remain open for an additional week.

### Election Process

The election will be conducted for one week from 25/4/2023 through 2/5/2023 and held through an online poll. Votes will be anonymous and anyone invested in the direction of O3DE and the SIG holding the election may vote. If you choose to vote, we ask that you be familiar with the nominees.

If there is a current interim chair, they will announce the results in the Discord sig channel as well as the SIG O3DE mailing list. If there is no interim chair, the Election Official will announce the results utilizing the same communication channels. At that time if there is a dispute over the result or concern over vote tampering, voting information will be made public to the extent that it can be exported from the polling system and the SIG will conduct an independent audit under the guidance of a higher governing body in the foundation.

**Comment by AMZN-Dk** [comment]
I will volunteer to operate as the election official for this process.

**Comment by Kadino** [comment]
I'll nominate myself. I am a current chair of this SIG, and am familiar with the duties. I'm also an active reviewer, frequently respond on Discord, and am a moderately active contributor. While my availability to contribute is sometimes limited, I'm happy to help maintain this SIG. 

I prefer to be referred to by my online handle Kadino. In Discord, I am Kadino#1734

**Comment by AMZN-Dk** [comment]
Election will be held starting on 25/4/2023 through 9/2/2023

**Comment by AMZN-Dk** [comment]
Doing a late update here. @Kadino Will remain on as Chair, @AMZN-Dk will serve as interim co-chair until a new co-chair can be defined.
